export const data = [
  {
    id: 1,
    first_name: "Tiebout",
    last_name: "Totton",
    department: "Marketing",
  },
  {
    id: 2,
    first_name: "Jarid",
    last_name: "Naper",
    department: "Accounting",
  },
  {
    id: 3,
    first_name: "Artie",
    last_name: "Enrdigo",
    department: "Business Development",
  },
  {
    id: 4,
    first_name: "Neddy",
    last_name: "McGebenay",
    department: "Sales",
  },
  {
    id: 5,
    first_name: "Estell",
    last_name: "Kohter",
    department: "Human Resources",
  },
  {
    id: 6,
    first_name: "Daniel",
    last_name: "Cutting",
    department: "Services",
  },
  {
    id: 7,
    first_name: "Gayla",
    last_name: "Mabson",
    department: "Business Development",
  },
  {
    id: 8,
    first_name: "Scottie",
    last_name: "Bernardino",
    department: "Training",
  },
  {
    id: 9,
    first_name: "Stillmann",
    last_name: "Warhurst",
    department: "Support",
  },
  {
    id: 10,
    first_name: "Steve",
    last_name: "Guinery",
    department: "Sales",
  },
  {
    id: 11,
    first_name: "Sonni",
    last_name: "Presidey",
    department: "Sales",
  },
  {
    id: 12,
    first_name: "Geraldine",
    last_name: "Gerardot",
    department: "Services",
  },
  {
    id: 13,
    first_name: "Bord",
    last_name: "Langdridge",
    department: "Engineering",
  },
  {
    id: 14,
    first_name: "Olenka",
    last_name: "Joynt",
    department: "Accounting",
  },
  {
    id: 15,
    first_name: "Raul",
    last_name: "Gentiry",
    department: "Legal",
  },
  {
    id: 16,
    first_name: "Marcus",
    last_name: "Inglese",
    department: "Accounting",
  },
  {
    id: 17,
    first_name: "Enrichetta",
    last_name: "Gillio",
    department: "Accounting",
  },
  {
    id: 18,
    first_name: "Mallorie",
    last_name: "Chuney",
    department: "Sales",
  },
  {
    id: 19,
    first_name: "Valle",
    last_name: "Jones",
    department: "Marketing",
  },
  {
    id: 20,
    first_name: "Edik",
    last_name: "Daintier",
    department: "Research and Development",
  },
];
